version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.2-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.squareup.moshi:moshi-kotlin
    versions:
    - 1.11.0
  - dependency-name: com.squareup.moshi:moshi
    versions:
    - 1.11.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: com.google.android.material:material
    versions:
    - 1.2.1
- package-ecosystem: gradle
  directory: "/termohome-common"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: junit:junit
    versions:
    - 4.13.1
- package-ecosystem: gradle
  directory: "/termohome-app"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.2-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: junit:junit
    versions:
    - 4.13.1
- package-ecosystem: gradle
  directory: "/termohome-iot"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.squareup.moshi:moshi-kotlin
    versions:
    - 1.11.0
  - dependency-name: com.squareup.moshi:moshi
    versions:
    - 1.11.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
